/* eslint-disable */
/**
 * This code was generated automatically by `pnpm generate` command
 * from GraphQL API schema (`./app/model/schema.graphql`).
 *
 * **DO NOT EDIT THIS FILE MANUALLY**
 */
import type * as Op from "./operations"
