name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main # Gałąź wywołująca deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kodu źródłowego
      - name: Checkout code
        uses: actions/checkout@v3

      # Skonfiguruj SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Skopiuj pliki aplikacji na EC2
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      # Zbuduj i uruchom aplikację na EC2
      - name: Build and start the app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/app &&
            npm install &&
            npm run build &&
            pm2 restart app || pm2 start npm --name 'app' -- start
          "
